version: '3'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app
    environment:
      - DEBUG=True
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 